[package]
name = "imageclass"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = "0.19.1"
clap = { version = "4.5.53", features = ["derive"] }
forust-ml = "0.4.8"
image = "0.25.9"
image_processing = "0.1.0"
imageproc = "0.25.0"
ndarray = "0.17.1"
polars = "0.52.0"
